### ISSUE TITLE
Garbled audio output with some MIDIs, when converting using OCv2

### ISSUE THREAD

**Issue by KaleidonKep99** [MyBlackMIDIScore/xsynth-clib#3]
Hi again...

I encountered an issue, where XSynth will randomly only output very garbled audio with some MIDIs, while working just fine with others.

I am not sure what the problem is really, since at first I just thought that I made some mistake in the allocation and disposal of the XSynth class, but it only seems to happen with *specific MIDIs*, while others work fine even after repeating the conversion process multiple times without restarting the app.

Here's an example of the kind of garbled output I get, plus a MIDI that got exported just fine after the first two:

https://github.com/user-attachments/assets/9ef3f712-1187-4883-bdb3-e53ab9967078

I can hook you up with a custom test build of OCv2, so that you can debug the issue, or I can just commit the latest changes so that you build it and debug it on your own.

**Comment by MyBlackMIDIScore** [comment]
That seems really odd... Considering also it only happens on specific MIDIs. The two MIDIs you rendered with this error render fine in Rust XSynth so it must be some kind of error in the C bindings.

> I can hook you up with a custom test build of OCv2, so that you can debug the issue, or I can just commit the latest changes so that you build it and debug it on your own.

Whatever is easier for you I guess, since it most likely is an issue with the library. But yeah I'd have to have a look myself at this.

**Comment by KaleidonKep99** [comment]
> That seems really odd... Considering also it only happens on specific MIDIs. The two MIDIs you rendered with this error render fine in Rust XSynth so it must be some kind of error in the C bindings.
> 
> > I can hook you up with a custom test build of OCv2, so that you can debug the issue, or I can just commit the latest changes so that you build it and debug it on your own.
> 
> Whatever is easier for you I guess, since it most likely is an issue with the library. But yeah I'd have to take a look myself at this.

Latest commit is up.

**Comment by MyBlackMIDIScore** [comment]
Sorry for asking all the time but I have been trying to get this to work for the past while but for some reason the values sent to XSynth are not what they are supposed to be. When starting a render and the soundfonts are being loaded, this is what XSynth receives: 
```
[src/soundfont.rs:122:9] &options = XSynth_SoundfontOptions {
    stream_params: XSynth_StreamParams {
        sample_rate: 2522871640,
        audio_channels: 32583,
    },
    bank: 0,
    preset: 0,
    linear_release: false,
    use_effects: false,
    interpolator: 0,
}
```
I did check though, the values in the internal OC struct are correct, they are just nuked in the way to XSynth. This is for the Linux build.

**Comment by KaleidonKep99** [comment]
> Sorry for asking all the time but I have been trying to get this to work for the past while but for some reason the values sent to XSynth are not what they are supposed to be. When starting a render and the soundfonts are being loaded, this is what XSynth receives:
> 
> ```
> [src/soundfont.rs:122:9] &options = XSynth_SoundfontOptions {
>     stream_params: XSynth_StreamParams {
>         sample_rate: 2522871640,
>         audio_channels: 32583,
>     },
>     bank: 0,
>     preset: 0,
>     linear_release: false,
>     use_effects: false,
>     interpolator: 0,
> }
> ```
> 
> I did check though, the values in the internal OC struct are correct, they are just nuked in the way to XSynth. This is for the Linux build.

They are also fine when I call GenDefault_StreamParams, so I am not sure really.
Maybe I am not supposed to reuse the same SoundfontOptions struct for multiple SFs?

**Comment by KaleidonKep99** [comment]
> > They are also fine when I call GenDefault_StreamParams, so I am not sure really.
> > Maybe I am not supposed to reuse the same SoundfontOptions struct for multiple SFs?
> 
> Yeah all the values are correct until they are received by XSynth. Maybe some kind of memory issue? I am not sure, but it happens on my host and on a VM (Linux only, Windows works fine).

After looking at your screenshot more carefully, I remember how strict C++ bindings are.
This fixed it!
![image](https://github.com/user-attachments/assets/08b9b31d-d7b4-446e-8bd6-4c0ebf61c963)

**Comment by KaleidonKep99** [comment]
![image](https://github.com/user-attachments/assets/8010860d-1fc5-44c2-86d1-c3e6a8c8aafd)

I noticed that calling GenDefault_SoundfontOptions internally calls GenDefault_StreamParams for the stream_params, so I tried doing this:

![image](https://github.com/user-attachments/assets/72fa537f-89c9-4f25-92ed-32d0b6c7ffed)

But I still get a garbled output.

**Comment by MyBlackMIDIScore** [comment]
> After looking at your screenshot more carefully, I remember how strict C++ bindings are.
This fixed it!
EDIT: Never mind it broke again, it seems to be random...

I tried this and it works fine now. Aside from `interpolator` with type `byte` but I changed this to a ushort/u16 in the API so it works fine now.
I will debug the issue now.

> But I still get a garbled output.

Yeah I don't think this issue is related to the stream parameters. I'll do some tests now and let you know though (if I even figure it out lol)

**Comment by KaleidonKep99** [comment]
> > After looking at your screenshot more carefully, I remember how strict C++ bindings are.
> > This fixed it!
> > EDIT: Never mind it broke again, it seems to be random...
> 
> I tried this and it works fine now. Aside from `interpolator` with type `byte` but I changed this to a ushort/u16 in the API so it works fine now. I will debug the issue now.
> 
> > But I still get a garbled output.
> 
> Yeah I don't think this issue is related to the stream parameters. I'll do some tests now and let you know though (if I even figure it out lol)

![image](https://github.com/user-attachments/assets/39541bf6-5519-4c3e-8b63-c36c9efdb39d)

Yeah, the stream params are fine even after being converted internally using "*convert_streamparams_to_rust*". I'll wait for you to figure out what the issue is... 💀

**Comment by MyBlackMIDIScore** [comment]
That took me an embarrassing amount of time to figure out, but I got it. It was an error with the pitch bend handling in the clib. I'll make a new commit in the next few minutes (after I test it a bit) that fixes it. Let me know if it will work when you try it.

Also one last thing, on the XSynth patch of OCv2 when I try to cancel the render the program segfaults or gives an error about a `free()` call and thus the until-then rendered audio never makes it to a file. The latest commit before XSynth works fine.

**Comment by KaleidonKep99** [comment]
Seems to work! Onto tackling the next issue...
